### PR TITLE
Improve issue template and README

### PR DESCRIPTION
**Pull request by tsalo**
Changes proposed:
- Add link to project proposal issue creation.
- Be more explicit about where to write contents in issue template.

### CODE REVIEW

**Comment by richford** [comment]
LGTM :rocket:

**Comment by dmoracze** [comment]
Looks good!

**Comment by dmoracze** [comment]
Thought:
```
<!-- Add the basic research question(s) your project will attempt to answer below this line -->
```
Means that we'll likely have this line included in the issue. You could say something like 
```
<!-- Replace this line with the basic research question(s) your project will attempt to answer -->
```

**Comment by tsalo** [comment]
@dmoracze the lines are comments, though, so they won't appear in the rendered issue. I worry that saying "replace" might lead folks to place their information between the comment strings (i.e., `<!--` and `-->`).

**Comment by dmoracze** [comment]
Ah ok, I think it's good then.

**Pull request merged**
